Add uart async task example
embassy-rs/embassy pull request #1037
Opened 2022-10-31 08:55 UTC by miathedev

Dear Embassy Team,

here i propose an additional async uart pass-through example for the STM32WL.

Because im quite new to Rust, is there something like **interfaces**?

The code: 
```
mut usart1: Uart<
        'static,
        embassy_stm32::peripherals::USART1,
        embassy_stm32::peripherals::DMA1_CH3,
        embassy_stm32::peripherals::DMA1_CH4,
    >,
    mut usart2: Uart<
        'static,
        embassy_stm32::peripherals::LPUART1,
        embassy_stm32::peripherals::DMA1_CH5,
        embassy_stm32::peripherals::DMA1_CH6,
    >,
```
is quite ugly in my opinion. I would like to allow any Type of DMA and USART/UART as argument. Is this possible somehow?
Im open to any feedback.

With love,
Mia

2022-10-31 10:03 UTC, lulf requested changes
Thanks for the PR! I added a few comments which should remove the need for the 'ugly' types. 

In general: Yes, there are interfaces in rust, called traits, but you need the full type in this case since the size of the toplevel embassy tasks must be known. However, you could also remove the embassy_executor::task macro and run the function from your main loop (but I suggest copying it all into the main loop instead).

The Uart peripherals implement some traits from the embedded-hal-async crate, similar to HALs for other chips. By importing `embedded_hal_async::serial::{Read, Write}`, you can create async functions like this:

```
async fn bridge<F, T>(from: F, to: T)
    where F: Read, T: Write
 {
    // Read from from, write to to.
}
```

2022-10-31 10:04 UTC, lulf commented on examples/stm32wl/src/bin/uart_async_task.rs
> +        Timer::after(Duration::from_secs(10)).await;
Rather than having an idle loop here, consider copying the loop from the passthrough task.

2022-11-01 07:29 UTC, miathedev commented
So. i hope i changed it correctly as you requested.
Btw. im totally now checking out Rust traits. Thank you so much!

2022-11-01 08:28 UTC, lulf approved these changes
Looks good to me! Maybe squash your commits, and then you can merge it yourself :)

bors d+

2022-11-01 08:47 UTC, miathedev commented
bors d+

2022-11-01 08:48 UTC, miathedev commented
bors r+

2022-11-01 08:59 UTC, merged