ADC support for STM32WLx
embassy-rs/embassy pull request #1864
Opened 2023-09-05 10:49 UTC by oll3

Waiting for https://github.com/embassy-rs/stm32-data/pull/246.

Will also remove the use of adccommon_v3 CCR register for STM32G0x. Since the CCR register definition for this device seems to have some bits/names swapped (VBATEN/TSEN) compared to the common one.

2023-09-05 21:56 UTC, xoviat requested changes

2023-09-05 21:56 UTC, xoviat commented on embassy-stm32/src/rcc/wl.rs
> +    pub adc_clock_source: AdcClockSource,
The adc clock source should be configured in the rcc mod and the clock frequency added to the clocks adc struct.

2023-09-05 23:31 UTC, xoviat commented
Can you rebase and update the metapac version?

2023-09-06 10:16 UTC, oll3 commented
> Can you rebase and update the metapac version?

Yep, rebased and bumped stm32-metapac!

2023-09-06 16:35 UTC, merged