wip: add can
embassy-rs/embassy pull request #20
Opened 2021-01-13 20:29 UTC by xoviat

2021-02-24 21:46 UTC, xoviat commented
cc @Dirbaio

2021-02-26 23:59 UTC, xoviat commented
dependency conflict: stm32-rs/bxcan#18

2021-03-03 20:52 UTC, marcelbuesing commented on embassy-stm32f4/Cargo.toml
> +bxcan = {version = "0.4.0", git= "https://github.com/jonas-schievink/bxcan.git", branch = "defmt02" }
Looks like this branch no longer exists but changes have been merged to
https://github.com/stm32-rs/bxcan

```toml
bxcan = { version = "0.4.0", git= "https://github.com/stm32-rs/bxcan.git", branch = "master" }
```

2021-03-06 00:08 UTC, Dirbaio commented on embassy-stm32f4/src/can.rs
> +    tx_int: interrupt::CAN1_TX,
the interrupts may be wrong if user doesn't use CAN1? 

How does `Instance` work in bxcan? the user has to implement it themselves for their chip?  Maybe we can provide the impls?

2021-03-06 00:09 UTC, Dirbaio commented
Looks great! I'm surprised so very little code is needed, nice!

Can you add an example?

2021-03-06 01:04 UTC, Dirbaio requested changes

2021-03-06 01:04 UTC, Dirbaio commented on embassy-stm32f4/src/can.rs
> +pub trait WithInterrupt: bxcan::Instance + private::Sealed {
This could simply be named `Instance`.

2021-03-06 01:04 UTC, Dirbaio commented on embassy-stm32f4/src/can.rs
> +    type RInstance;
add ` : Interrupt` trait bounds here

2021-03-06 01:04 UTC, Dirbaio commented on embassy-stm32f4/src/can.rs
> +    type RInstance;
Maybe name TxInterrupt/RxInterrupt? They're not peripheral instances, they're interrupts

2021-03-06 01:04 UTC, Dirbaio commented on embassy-stm32f4/src/can.rs
> +pub struct Can<T: bxcan::Instance, TINT: Interrupt, RINT: Interrupt> {
There's no need for having 3 generic params anymore. Makes the type simpler:

```rust
pub struct Can<T: Instance> {
    can: bxcan::Can<T>,
    tx_int: T::TxInterrupt,
    rx_int: T::RxInterrupt,
}
```

2021-03-06 01:19 UTC, xoviat commented
This needs to go back to draft, because the defmt update caused problems.

2021-03-06 01:40 UTC, xoviat commented
pending stm32-rs/bxcan#21

2021-03-17 21:54 UTC, merged