RP2040 PWM higher-level API
embassy-rs/embassy pull request #2882
Opened 2024-04-27 17:02 UTC by cylewitruk

Renamed the branch on my end which automatically closed PR #2855 - this PR is the continuation.

2024-04-28 11:22 UTC, cylewitruk commented
> Yes, that's exactly right! This can be resolved with macros, but it is nice to be able to do conventional, easy-to-follow Rust programming to handle lots of slices/pins/whatever, instead of being stuck with macros or boilerplate or -- often -- both at once. 

Couldn't agree more about trying to be as Rust-idiomatic as possible 😊

>Generics would also be a solution for this, but the extra heap allocations may be unacceptable for some environments -- which I think just leaves the user with transmuting and not much else.

In this case everything is static dispatch and expanded at compile-time (and thus you can also enforce constraints at compile-time as well) - I don't think dynamic dispatch (trait objects) are used anywhere -- anyway, I agree that avoiding them is paramount in embedded.

> Anyways, it's not a huge deal -- and if it doesn't fit with the rest of embassy-rs, it's totally reasonable to just do it in a way that matches the precedent in this library if you want. Just wanted to list everything I thought of!

That's what I was looking for 😊 In general I think that three layers of indirection would be good for a suite like embassy to enable all forms of :
1. The PAC (very-low-level, direct access to HW)
2. Intermediate HAL API's (like the current state of the PWM API's)
3. Self-documenting builders/configurators on top of pt. 2 (and pt. 1 where necessary).
That would enable clear code for many cases but A) not break compatibility for current users, and B) be beginner-friendly without hindering advanced usage where needed.

Nothing that's been discussed with the embassy maintainers yet, but hoping they'll chime in here soon enough 😅 I'm personally new to embassy so I'm writing mostly out of my own "what I would have liked" perspective. Having to refer so much to the datasheet, which in itself can be found lacking/confusing, isn't super productive haha...

2024-04-28 11:24 UTC, cylewitruk commented
> Yes, that's exactly right! This can be resolved with macros, but it is nice to be able to do conventional, easy-to-follow Rust programming to handle lots of slices/pins/whatever, instead of being stuck with macros or boilerplate or -- often -- both at once. 

Couldn't agree more about trying to be as Rust-idiomatic as possible 😊

>Generics would also be a solution for this, but the extra heap allocations may be unacceptable for some environments -- which I think just leaves the user with transmuting and not much else.

In this case everything is static dispatch and expanded at compile-time (and thus you can also enforce constraints at compile-time as well) - I don't think dynamic dispatch (trait objects) are used anywhere -- anyway, I agree that avoiding them is paramount in embedded.

> Anyways, it's not a huge deal -- and if it doesn't fit with the rest of embassy-rs, it's totally reasonable to just do it in a way that matches the precedent in this library if you want. Just wanted to list everything I thought of!

That's what I was looking for 😊 In general I think that three layers of indirection would be good for a suite like embassy to enable all forms of :
1. The PAC (very-low-level, direct access to HW)
2. Intermediate HAL API's (like the current state of the PWM API's)
3. Self-documenting builders/configurators on top of pt. 2 (and pt. 1 where necessary).
That would enable clear code for many cases but A) not break compatibility for current users, and B) be beginner-friendly without hindering advanced usage where needed.

Nothing that's been discussed with the embassy maintainers yet, but hoping they'll chime in here soon enough 😅 I'm personally new to embassy so I'm writing mostly out of my own "what I would have liked" perspective. Having to refer so much to the datasheet, which in itself can be found lacking/confusing, isn't super productive haha...

With all of that said, would you mind trying the latest version? I can't for the life of me to get my Pico W to output _anything_. I added your "bouncy" example to the rp-examples and not even that works for me... 🤔

2024-04-29 20:04 UTC, crabdancing commented
The example looks fine to me :)
![IMG_20240429_135956](https://github.com/embassy-rs/embassy/assets/28266167/9674ee95-989c-4f00-9b74-21e41f49fab3)

2024-04-30 05:37 UTC, cylewitruk commented
> Looks like it keeps working if I change it up to 41 MHz, or down to 8 Hz. I'm not sure why I can't get it above 41Mhz, but that seems ok for most use cases.

Can you get a better representation if you use 10x?

> The only potential significant issue I see is that it's showing 508Hz for both of us, instead, of 500.
> 
> If I do:
> 
> ```
> .frequency(Frequency::Hz(500 - 8))
> ```
> 
> I finally get exactly 500 Hz. Also if I change it to 600, I end up getting 612. Not sure if the oscilloscopes are inaccurate or if there's something slightly wrong with the math.

There could definitely be something slightly off with the fractional divider... seems it's a bigger problem down in Hz, if I set 30KHz then I get 30KHz spot-on on the scope. [Here's the math code](https://github.com/embassy-rs/embassy/pull/2882/files#diff-a1f1cbd7109dd6f6dba2366fbb29fef1603c7189b33be246cd02b554aec819b4R240) - do you see anything that could be improved?

2024-04-30 20:58 UTC, cylewitruk commented
Note: API has been updated to accept slice/pins in the `apply` method, so configurations are slice/pin agnostic.

```rust
// Initialize peripherals
let peripherals = embassy_rp::init(Default::default());

let slice0 = Pwm::builder()
    .free_running()
    .frequency(Frequency::Hz(30_000))
    .phase_correct(false)
    .with_output_a(|a| a.duty_cycle(50.0))
    .with_output_b(|b| b.duty_cycle(75.0))
    .apply(peripherals.PWM_SLICE0, peripherals.PIN_16, peripherals.PIN_17)
    .unwrap();

slice0.enable();
```

2024-04-30 21:58 UTC, crabdancing commented
Awesome! I'll try to comb through it later and help, if I manage to get some free time. Are there specific formulas in the RP2040 datasheet I can reference? It's >600 pages, so it's kinda hard to sort through. :P

2024-04-30 22:49 UTC, cylewitruk commented
> Awesome! I'll try to comb through it later and help, if I manage to get some free time. Are there specific formulas in the RP2040 datasheet I can reference? It's >600 pages, so it's kinda hard to sort through. :P

Haha, tell me about it :sweat_smile: Everything PWM is in section 4.5 with some formulas on page 531.

> Edit: if that fails, might also be worth checking out the C++ SDK to see what logic they're doing. Or maybe open an issue with the Raspberry Pi people? 🤔

Yeah I've looked there and at other implementations as well as related forum Q's -- if it was just trying to get a specific duty cycle then we could just use 10,000 as `TOP` and then compare is easy to calculate. It's when trying to account for both frequency _and_ duty % where it gets a little hairy, because `DIV` and `TOP` are what set the slice's frequency, which needs to be calculated first and _then_ the compare value can be calculated based on that `TOP` value...

2024-05-02 16:44 UTC, cylewitruk commented
@Dirbaio Invite you to take a quick peek at this PR while I'm buttoning it up in-case you have any design/code comments before I convert it from draft 🙏 I'm working on polishing the level/edge-sensitive areas as well as introducing a high-accuracy u32 counter with help of DMA until then.

2024-05-03 18:53 UTC, crabdancing commented
@cylewitruk Sorry about not testing this for awhile. My picoprobe got fried somehow, and I have to make another. I'll check it out sometime today if I can make the time to build another one.

2024-05-03 19:06 UTC, cylewitruk commented
> @cylewitruk Sorry about not testing this for awhile. My picoprobe got fried somehow, and I have to make another. I'll check it out sometime today if I can make the time to build another one.

Ouch! No worries, I'm wrestling with the input side and DMA atm and hoping to get some feedback from maintainers in the meantime 😊

2024-05-14 22:28 UTC, crabdancing commented
Sorry, my job had to pivot to a bunch of frontend stuff and I couldn't find the time to build another picoprobe until just now. The code is working beautifully! Thanks so much for your work on this, @cylewitruk! I tested it all the way down to 8Hz, and it works all the way up to 40 Mhz! :) And the 500 Hz example is spot on, on my test rig, too. Awesome stuff.

2024-05-14 22:56 UTC, crabdancing commented
After some further testing, there's some sort of bug in the calculations for `set_duty_cycle`, as my latest pull of `feat/rp2040-pwm-api` gives a panic with `Frequency below is too high` when trying to call `set_duty_cycle` -- even though the frequency set is well within supported frequencies:

```rs
//! This example shows how to use PWM (Pulse Width Modulation) in the RP2040 chip.
//!
//! The LED on the RP Pico W board is connected differently. Add a LED and resistor to another pin.

#![no_std]
#![no_main]

use defmt::info;
use embassy_executor::Spawner;
use embassy_rp::pwm::prelude::*;
use embassy_time::{Duration, Timer};
use {defmt_rtt as _, panic_probe as _};

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    // Initialize peripherals
    let peripherals = embassy_rp::init(Default::default());

    let mut slice0 = Pwm::builder()
        .free_running()
        .frequency(Frequency::Hz(100_000))
        .phase_correct(false)
        .with_output_a(|a| a.duty_cycle(100.0))
        .with_output_b(|b| b.duty_cycle(75.0))
        .apply(peripherals.PWM_SLICE0, peripherals.PIN_16, peripherals.PIN_17)
        .unwrap();

    slice0.enable();

    slice0.set_duty_cycle(embassy_rp::pwm::v2::Channel::A, 50.0).unwrap();
    slice0.set_duty_cycle(embassy_rp::pwm::v2::Channel::B, 50.0).unwrap();
    loop {
        info!("tick!");
        // Wait for a second
        Timer::after(Duration::from_secs(5)).await;
    }
}
```

Here's the output:

```rs
0.008311 DEBUG Setting A pin function to PWM
└─ embassy_rp::pwm::builder::free_running::{impl#16}::new_from_config @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.008904 DEBUG
Freq = 100000.0
Top = 1249
Div = 0x01.0
Out = 100000.0
└─ embassy_rp::pwm::v2::{impl#6}::calculate_div_and_top @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.009268 DEBUG Changing frequency to 100000Hz (from Hz=125000000, TOP=65536, DIV=1)
└─ embassy_rp::pwm::v2::{impl#6}::reconfigure @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.009566 DEBUG Frequency changed to 100000Hz (TOP=1249, DIV=16)
└─ embassy_rp::pwm::v2::{impl#6}::reconfigure @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.009815 DEBUG Updating compare value for channel A to 1249
└─ embassy_rp::pwm::v2::{impl#6}::reconfigure @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.010066 DEBUG Setting B pin function to PWM
└─ embassy_rp::pwm::builder::free_running::{impl#16}::new_from_config @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.010352 DEBUG
Freq = 100000.0
Top = 1249
Div = 0x01.0
Out = 100000.0
└─ embassy_rp::pwm::v2::{impl#6}::calculate_div_and_top @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.010669 DEBUG No changes have been made to the frequency (100000Hz).
└─ embassy_rp::pwm::v2::{impl#6}::reconfigure @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.010822 DEBUG Updating compare value for channel B to 936
└─ embassy_rp::pwm::v2::{impl#6}::reconfigure @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:130
0.011098 ERROR panicked at 'Frequency below is too high ...'
└─ embassy_rp::pwm::v2::{impl#6}::calculate_div_and_top @ /home/ada/Projects/rs/embassy-cylwit/embassy-rp/src/fmt.rs:106
0.011245 ERROR panicked at /home/ada/.cargo/registry/src/index.crates.io-6f17d22bba15001f/defmt-0.3.6/src/lib.rs:368:5:
explicit panic
└─ panic_probe::print_defmt::print @ /home/ada/.cargo/registry/src/index.crates.io-6f17d22bba15001f/panic-probe-0.3.1/src/lib.rs:104
```

That said, the init code is at least doing exactly what it's supposed to. I see `set_duty_cycle` and `apply` both call `reconfigure` (albeit with some intermediate funcs in the call stack) so the bug is probably caused by a step that `apply`/`new_from_config` do that is not happening with a simple `reconfigure` call by itself (as is done by `set_duty_cycle`).

Anyways, great job again! I think its almost perfect. :3

2024-05-16 10:47 UTC, cylewitruk commented
@crabdancing I've also been a bit busy the last week so haven't spent much time here -- thanks for finding that! I'll try to look at that in the coming days 😄 Really happy that the init code seems to be working fine now though, that means that the math in that path is at least correct 😅

2024-06-12 13:27 UTC, mikkelens commented on examples/rp/src/bin/pwm_bounce.rs
This needs a file/example level explanation like the others e.g. the top of `pwm_counter.rs`

2024-06-12 13:33 UTC, mikkelens requested changes
I can't test this, but it certainly looks preferable to having no high level API. Examples are missing some documentation/explanations though, see comments.

2024-06-12 13:33 UTC, mikkelens commented on examples/rp/src/bin/pwm.rs
It would be good with an explanation of what this does (even if the explanation did not exist for the previous/non-builder API.
[Same goes](https://github.com/embassy-rs/embassy/pull/2882/files#r1636465149) for the new `pwm_bounce.rs`.

2024-07-05 16:38 UTC, vasilNnikolov commented
I'm a bit late to the party, but a kind feature request would be to implement [the standard `embedded-hal` trait for PWM](https://docs.rs/embedded-hal/latest/embedded_hal/pwm/trait.SetDutyCycle.html). I can lend a hand on that if you're not keen on implementing it yourself.

2024-07-30 12:50 UTC, cylewitruk commented
> I'm a bit late to the party, but a kind feature request would be to implement [the standard `embedded-hal` trait for PWM](https://docs.rs/embedded-hal/latest/embedded_hal/pwm/trait.SetDutyCycle.html). I can lend a hand on that if you're not keen on implementing it yourself.

Be my guest! I've been a bit busy and then vacation so haven't gotten around to buttoning this up just yet.

2024-07-30 12:52 UTC, cylewitruk commented
> I can't test this, but it certainly looks preferable to having no high level API. Examples are missing some documentation/explanations though, see comments.

Just getting back, so will have a look at getting this done. Thanks for the review :)

2024-07-30 19:41 UTC, crabdancing commented
Awesome :D I was worried this amazing work might never be picked up again. I'm excited to see what you commit! :3

2026-07-26 11:20 UTC, Dirbaio commented
Hello,

The pull request backlog on the Embassy repo has grown uncontrollably. In an effort to clean it up, we're declaring "pull request bankruptcy" and closing all pull requests older than 1 year.

We've added a new [review queue](https://github.com/embassy-rs/embassy/blob/main/CONTRIBUTING.md) that works in a FIFO way, to avoid pull request reviews stalling for so long in the future.

If you're still interested in contributing this PR, you're welcome to open a new one. Please rebase on top of latest main branch if you do so the changes merge cleanly.

Thank you for your understanding!

2026-07-26 11:20 UTC, closed without merging