PeripheralMutex: Remove Pin
embassy-rs/embassy pull request #327
Opened 2021-07-29 12:09 UTC by Dirbaio

Fixes #323

2021-08-01 22:02 UTC, thalesfragoso requested changes
Great work, looks way better now. Just left some small nits.

2021-08-01 22:02 UTC, thalesfragoso commented on examples/stm32h7/src/bin/eth.rs
> +static STATE: Forever<State<'static, 4, 4>> = Forever::new();
Don't need `Forever` if `State::new()` is a `const fn`.

2021-08-01 22:27 UTC, thalesfragoso commented on examples/stm32h7/src/bin/eth.rs
> +static STATE: Forever<State<'static, 4, 4>> = Forever::new();
Actually no, since we need `&mut`, which would mean `unsafe` without `Forever`.

2021-08-02 09:56 UTC, Dirbaio commented on embassy-hal-common/src/peripheral.rs
> +    pub fn new() -> Self {
I tried! but it requires nightly-only "fancy generics in consts". Not sure what policy we have on that...

2021-08-02 10:52 UTC, Dirbaio commented on embassy-stm32/src/eth/v2/mod.rs
>      pub fn new(
Done

2021-08-02 10:52 UTC, Dirbaio commented on embassy-hal-common/src/usb/mod.rs
> +    pub fn new<S: IntoClassSet<B, T>>(
Done

2021-08-02 15:18 UTC, thalesfragoso commented on embassy-hal-common/src/usb/mod.rs
> +    pub fn new() -> Self {
Sorry, my bad, this has bounds... Probably not worth going the `heapless::i` route.

2021-08-02 17:50 UTC, Dirbaio commented on embassy-hal-common/src/peripheral.rs
> +    pub fn new() -> Self {
Okay, constified this and the ETH state.

2021-08-02 18:28 UTC, thalesfragoso approved these changes
Beautiful, thanks!

2021-08-02 18:28 UTC, merged